source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "~> 3.2.0"

gem "rails", "~> 7.1.0"
gem "mysql2", "~> 0.5"
gem "puma", "~> 6.0"
gem "jbuilder"
gem "bootsnap", ">= 1.4.4", require: false

# Reduce boot time and avoid needing tzinfo-data on Linux
gem "tzinfo-data", platforms: %i[windows jruby]

group :development, :test do
  gem "rspec-rails", "~> 6.1"
  gem "factory_bot_rails"
  gem "faker"
  gem "debug", platforms: %i[mri windows]
end

group :test do
  gem "database_cleaner-active_record"
end
